"""Fix

Revision ID: 818ba0c223f7
Revises: f255c83b1dba
Create Date: 2025-12-04 13:12:34.055574

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "818ba0c223f7"
down_revision: Union[str, Sequence[str], None] = "f255c83b1dba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add updated_at column as nullable first, then update values, then set not null
    op.add_column("tags", sa.Column("updated_at", sa.DateTime(), nullable=True))

    # Set a default value for existing rows (use created_at or current timestamp)
    op.execute("UPDATE tags SET updated_at = created_at")

    # Now make it NOT NULL
    op.alter_column("tags", "updated_at", nullable=False)

    # Create indexes (these should work fine)
    op.create_index("idx_book_author", "books", ["author"])
    op.create_index("idx_book_created", "books", ["created_at"])
    op.create_index("idx_book_title", "books", ["title"])
    op.create_index("idx_book_user", "books", ["user_uid"])
    op.create_index("idx_review_created", "reviews", ["created_at"])
    op.create_index("idx_review_rating", "reviews", ["rating"])
    op.create_index("idx_review_user_book", "reviews", ["user_uid", "book_uid"])
    op.create_index("idx_tag_name", "tags", ["name"], unique=True)
    op.create_index("idx_user_email", "users_table", ["email"], unique=True)
    op.create_index("idx_user_username", "users_table", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_username", table_name="users_table")
    op.drop_index("idx_user_email", table_name="users_table")
    op.drop_index("idx_tag_name", table_name="tags")
    op.drop_index("idx_review_user_book", table_name="reviews")
    op.drop_index("idx_review_rating", table_name="reviews")
    op.drop_index("idx_review_created", table_name="reviews")
    op.drop_index("idx_book_user", table_name="books")
    op.drop_index("idx_book_title", table_name="books")
    op.drop_index("idx_book_created", table_name="books")
    op.drop_index("idx_book_author", table_name="books")
    op.drop_column("tags", "updated_at")
    # ### end Alembic commands ###
