"""add password hash field

Revision ID: 81d328153efa
Revises: 91181af4b2d6
Create Date: 2025-11-29 11:44:46.899096

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '81d328153efa'
down_revision: Union[str, Sequence[str], None] = '91181af4b2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'password_hash')
    # ### end Alembic commands ###
