"""add book tags table

Revision ID: f255c83b1dba
Revises: 14a976f15952
Create Date: 2025-12-02 15:29:51.657025

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'f255c83b1dba'
down_revision: Union[str, Sequence[str], None] = '14a976f15952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
